from enum import Enum


class OrganizationType(str, Enum):
    PLATFORM = "PLATFORM"
    MANUFACTURER = "MANUFACTURER"
    DISTRIBUTOR = "DISTRIBUTOR"
    PHARMACY = "PHARMACY"
    LOGISTICS_HUB = "LOGISTICS_HUB"


class OrganizationRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"

    COMPANY_ADMIN = "COMPANY_ADMIN"
    COMPANY_OPERATOR = "COMPANY_OPERATOR"
    SALES_REPRESENTATIVE = "SALES_REPRESENTATIVE"

    PHARMACY_OWNER = "PHARMACY_OWNER"
    PHARMACY_BUYER = "PHARMACY_BUYER"

    HUB_MANAGER = "HUB_MANAGER"
    HUB_OPERATOR = "HUB_OPERATOR"

    DELIVERY_MANAGER = "DELIVERY_MANAGER"
    DRIVER = "DRIVER"

    FINANCE_ADMIN = "FINANCE_ADMIN"