"""create products table

Revision ID: 16589014b8ab
Revises: 598c2f7f570f
Create Date: 2026-09-15 22:13:44.871181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16589014b8ab'
down_revision: Union[str, Sequence[str], None] = '598c2f7f570f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generic_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('pack_size', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generic_id'], ['generics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand_name'), 'products', ['brand_name'], unique=False)
    op.create_index(op.f('ix_products_generic_id'), 'products', ['generic_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_manufacturer_id'), 'products', ['manufacturer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_manufacturer_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_generic_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
