"""create inventory_lots table

Revision ID: b86898851642
Revises: 19ddf6253fbf
Create Date: 2026-09-15 23:13:07.007386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86898851642'
down_revision: Union[str, Sequence[str], None] = '19ddf6253fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_lots_batch_number'), 'inventory_lots', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_lots_depot_id'), 'inventory_lots', ['depot_id'], unique=False)
    op.create_index(op.f('ix_inventory_lots_id'), 'inventory_lots', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_lots_product_id'), 'inventory_lots', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_lots_product_id'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_id'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_depot_id'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_batch_number'), table_name='inventory_lots')
    op.drop_table('inventory_lots')
    # ### end Alembic commands ###
